import userRoute from "./v1/user.route";
import authRoute from "./v1/auth.route";
import jobRoute from "./v1/job.route";
import applicationRoute from "./v1/application.route";
import analyticsRoute from "./v1/analytics.router";
import resumeAnalyzerRoute from "./v1/resumeAnalyzer.router";
import { Router } from "express";
import statsRoute from "./v1/stats.route";
const router = Router();
router.use("/user", userRoute);
router.use("/auth", authRoute);
router.use("/job", jobRoute);
router.use("/application", applicationRoute);
router.use("/stats", statsRoute);
router.use("/analytics", analyticsRoute);
router.use("/", resumeAnalyzerRoute);
export default router;